name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run Flake8
      run: |
        flake8 ./selenium_chrome/source/log/* ./selenium_chrome/source/modules/* ./selenium_chrome/source/main.py

    - name: Run Black
      run: |
        black --check ./selenium_chrome/source/log/* ./selenium_chrome/source/modules/* ./selenium_chrome/source/main.py
